### ISSUE TITLE
Can Not Open or Convert Amplitude 2016 .png_ps4

### ISSUE THREAD

**Issue by codemasterv** [maxton/LibForge#36]
Hello,

I have compiled the most recent version of this tool. It states it supports png_ps4 to png but with Amplitude 2016 PS4 it errors on attempt to open or convert to PNG.

Is PS4 Amp2016 not supported? Do you have any tips or advice. 

_______________________________________________________________________________________________________

Error shown in command window:

G:\Amplitude\Assest_Tools\3_ForgeTool>ForgeTool.exe tex2png warning.png_ps4 warning1.png

Unhandled Exception: System.Exception: Invalid array size FFFFFFFF encountered at CC8. File is corrupt or not understood.
   at LibForge.Util.BinReader.FixedArr[T](Func`1 constructor, UInt32 size) in C:\forge\libforge\LibForge\LibForge\LibForge\Util\BinReader.cs:line 81
   at LibForge.Util.BinReader.Arr[T](Func`1 constructor, UInt32 maxSize) in C:\forge\libforge\LibForge\LibForge\LibForge\Util\BinReader.cs:line 93
   at LibForge.Texture.TextureReader.Read() in C:\forge\libforge\LibForge\LibForge\LibForge\Texture\TextureReader.cs:line 37
   at LibForge.Texture.TextureReader.ReadStream(Stream s) in C:\forge\libforge\LibForge\LibForge\LibForge\Texture\TextureReader.cs:line 14
   at ForgeTool.Program.<>c.<Main>b__0_4(Stream fi, Stream fo) in C:\forge\libforge\LibForge\LibForge\ForgeTool\Program.cs:line 65
   at ForgeTool.Program.<Main>g__WithIO|0_0(Action`2 action, <>c__DisplayClass0_0& ) in C:\forge\libforge\LibForge\LibForge\ForgeTool\Program.cs:line 33
   at ForgeTool.Program.Main(String[] args) in C:\forge\libforge\LibForge\LibForge\ForgeTool\Program.cs:line 63

G:\Amplitude\Assest_Tools\3_ForgeTool>

**Comment by codemasterv** [comment]
![Capture](https://user-images.githubusercontent.com/23326730/124175477-48a81000-da73-11eb-8481-948f2a661a6b.PNG)

Screen Shot

**Comment by pulsed3x** [comment]
sorry but he is dead. no joke so he can't help https://docs.google.com/document/d/1GXXJZ0WXrtUYbIrFUwzUawRObjg2hNpoba6HLRcPQ1A/edit
